Feature/38 seb
CntoDev/cnto-additions-old pull request #40
Opened 2021-01-01 14:34 UTC by Seb105

- Remove grease dot from AH-9
- Add collimator style aiming reticle to AH-6 and AH-9
- CBA settings to configure feature

2021-01-02 12:08 UTC, milivojm reviewed
I recommend moving rectacle.paa to cnto-assets to keep this clean and small. Images, sounds and other multimedia files are meant to be placed there and referenced here.

2021-01-02 12:12 UTC, milivojm commented on addons/littlebird_hud/fn_init.sqf
> +	false   /* needRestart */
Please double check if this argument is needed. Documentation (https://cbateam.github.io/CBA_A3/docs/files/settings/fnc_init-sqf.html) doesn't use it.

2021-01-02 12:15 UTC, milivojm commented on addons/littlebird_hud/fn_init.sqf
> +if (!hasInterface) exitWith {};
Hit enter before and after blocks for readability.

2021-01-02 12:19 UTC, milivojm commented on addons/littlebird_hud/fn_init.sqf
> +	waitUntil { !isNull player };
Please add `sleep` for performance reasons.

2021-01-02 12:30 UTC, milivojm commented on addons/littlebird_hud/fn_init.sqf
> +		if (_newVehicle isKindOf "RHS_MELB_AH6M" OR _newVehicle isKindOf "Heli_Light_01_armed_base_F" && a3aa_littlebird_hud_enable) then {
Not sure I understand your intent properly but `&&` will execute before `OR`. This means **RHS_MELB_AH6M** will always have the UI change applied, no matter the value of `a3aa_littlebird_hud_enable` setting. Was that on purpose or?

https://community.bistudio.com/wiki/Operators#Rules_of_Precedence

2021-01-02 12:43 UTC, Seb105 commented on addons/littlebird_hud/fn_init.sqf
> +		if (_newVehicle isKindOf "RHS_MELB_AH6M" OR _newVehicle isKindOf "Heli_Light_01_armed_base_F" && a3aa_littlebird_hud_enable) then {
Correct but I think that it is a leftover check, a3aa_littlebird_hud_enable is immediately checked by the called function anyway, so I will remove this unecessary check.

2021-01-02 12:48 UTC, Seb105 commented on addons/littlebird_hud/fn_init.sqf
> +	false   /* needRestart */
CBA Documentation is out of date. https://cbateam.github.io/CBA_A3/docs/files/settings/fnc_addSetting-sqf.html is the correct documentation, which actually just calls CBA_settings_fnc_init itself. Not sure why there are 2 functions that do the exact same thing (literally) with different documentation.

2021-01-02 12:56 UTC, Seb105 reviewed
> I recommend moving rectacle.paa to cnto-assets to keep this clean and small. Images, sounds and other multimedia files are meant to be placed there and referenced here.

Don't agree, files important to an addon should be found in close proximity to where they're actually used. This would create an unecessary dependency on cnto-assets

2021-01-02 12:57 UTC, Seb105 commented on addons/littlebird_hud/fn_init.sqf
> +	waitUntil { !isNull player };
Nowhere else does cnto-additions do this. I've copied the code style from the rest of the addon, why change it here?

2021-01-02 15:56 UTC, milivojm commented on addons/littlebird_hud/fn_hud.sqf
> +private _offsetEye = [false,true] select (_vehicle isKindOf "RHS_MELB_AH6M");
`_vehicle isKindOf "RHS_MELB_AH6M"` returns a boolean itself.

2021-01-03 09:51 UTC, milivojm requested changes
Grease dot remains the problem, I've tried looking for it in the selections, object textures and model (no luck). It's not a custom display either nor a control attached to display 46. Think all that is left is trying to override properties of the class in the config file one by one until you luckily hit the one that adds that grease dot.

As far as paa location, since it is small, it can remain where it is now.

2021-01-03 09:52 UTC, milivojm commented on addons/littlebird_hud/config.cpp
> +    class littlebird_hud {
a3aa_ missing from class name.

2021-01-03 13:10 UTC, freghar commented
(Not reviewing, but since I ran into a similar thing years ago, saving you some time here.)

You cannot easily remove the "grease dot". It's in `rhsusf_melb/Data/optics/melb_crosshair_dot_ca.paa` and was directly referenced when the `melb.p3d` model was built, which you would need to rebuild (and have access to the source files). There seems to also be a `.rvmat` for it, also directly referenced from `.p3d`.

There is
```
        class AnimationSources: AnimationSources {
            class Addcrosshair {
                source = "user";
                animPeriod = 1;
                initPhase = 1;
            };
```
but I doubt it's either related to the dot, or that the dot has more than one animation phase.

The code tries to set texture for something unrelated,
```
        hiddenSelections[] = {"camo1", "d_SN"};
        hiddenSelectionsTextures[] = {"rhsusf\addons\rhsusf_melb\data\melb_ext_co.paa", "rhsusf\addons\rhsusf_melb\data\decals\SN\blank_ca.paa"};
```
I'm not quite sure what "SN" means, there's quite a few `.paa`s with barely visible numbers (no clue what for), but the referenced `blank_ca.paa` is just a blank transparent image, not a grease dot.

It should be possible, I think, to override the RHS paa with a dedicated `pbo` which depends on `rhsusf_melb` (is loaded after it) and uses `rhsusf\addons\rhsusf_melb` as PBOPREFIX and has a blank/transparent `.paa` on the same path as the original one. However, I don't remember if this actually works or if you'd need to copy over all of the files. Alternatively, you could easily patch the existing RHS `pbo`, but it would need modification on every RHS update.

2021-01-03 17:04 UTC, milivojm commented
I had some luck with grease dot. 

`lb animateSource ["Addcrosshair", 0, true];`

This seems to remove the dot by animating adding crosshair in phase 0 (no dot displayed). `lb` is my random variable for littlebird (in editor) so use something like `_vehicle` in your script.

2021-01-03 22:03 UTC, milivojm approved these changes
Nice! Thank you!

2021-01-03 22:04 UTC, merged